name: Build - Run Community Board Budget Requests (CBBR) Update 

on:
  workflow_dispatch:
    inputs:
      run_build:
        description: "Run the CBBR Build"
        type: boolean
        required: true
        default: false
      run_export:
        description: "Run Export Step and Upload to DO"
        type: boolean
        required: true
        default: false
jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgis/postgis:12-3.0-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      BUILD_ENGINE: postgresql://postgres:postgres@localhost:5432/postgres
      EDM_DATA: ${{ secrets.EDM_DATA }}
      AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2


      - name: install dependencies ...
        run: |
          sudo apt update
          sudo apt install -y gdal-bin
          curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv ./mc /usr/bin
          mc alias set spaces $AWS_S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY --api S3v4
          sudo apt install python3-pip
          pip3 install requirements.txt

