name: Test

on:
  push:
  workflow_dispatch:

jobs:
  branch_lint:
    name: Linting tests - python
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11.1"

      - name: setup
        run: pip install black==22.8.0

      - name: black linter
        run: black --diff --check ./

  branch_unit_tests:
    name: Unit tests
    runs-on: ubuntu-20.04
    # container:
    #   image: nycplanning/docker-geosupport:latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: use geosupport docker image in this step
        uses: nycplanning/docker-geosupport:latest
        run: |
          python3 -m pip list

      - name: some tests [PLACEHOLDER]
        run: |
          echo "running tests ..."

  # branch_build_tests:
  #   name: Build tests
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     logging_level: "DEBUG"
  #   secrets: inherit
