name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test_lint:
    name: Linting tests
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11.1"

      - name: setup
        run: pip install black==22.8.0

      - name: black linter
        run: black --diff --check ./

  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: nycplanning/docker-geosupport:latest
      env:
        RUN_ENV: test
      volumes:
        - ${{ github.workspace }}:/home/db-cbbr
      options: -w /home/db-cbbr
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Run pytest
        run: |
          set -e
          cd cbbr_build
          python3 -m pip list
          # python3 -m pip install --requirement requirements.txt
          # python3 -m pip install pytest
          python3 -m pip list
          python3 -m pytest

  test_unit:
    name: Unit tests
    runs-on: ubuntu-20.04
    # container:
    #   image: nycplanning/docker-geosupport:latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # - name: run pytest via geosupport image A
      #   uses:
      #     docker://nycplanning/docker-geosupport:latest
      #     # run: |
      #     #   set -e
      #     #   cd cbbr_build
      #     #   python3 -m pip list

      - name: run pytest via geosupport image
        uses: addnab/docker-run-action@v3
        with:
          image: nycplanning/docker-geosupport:latest
          options: -v ${{ github.workspace }}:/home/db-cbbr -w /home/db-cbbr
          shell: bash
          run: |
            set -e
            cd cbbr_build
            python3 -m pip list
            # python3 -m pip install --requirement requirements.txt
            # python3 -m pip install pytest
            python3 -m pip list
            python3 -m pytest

      - name: some tests [PLACEHOLDER]
        run: |
          echo "running tests ..."

  # test_build:
  #   name: Build tests
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     logging_level: "DEBUG"
  #   secrets: inherit
